url: http://devopsautomators.io

# Site settings
title: Devopsautomators
tagline: We are software delivery pipeline automation experts!
email: info@devopsautomators.io 
description: "Devopsautomators are experts in automating your software delivery process. We are experienced engineers with a focus on making things work better."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333
  blue: 00b3fe
  green: 8fcb00

# Team names, titles and social links
people:
- name: Michiel Sens 
  pic: 1
  tagline: CD Enthousiast
  social:
    - title: github
      url: https://github.com/msens
    - title: linkedin 
      url: https://nl.linkedin.com/pub/michiel-sens/0/716/9a5

- name: Adriaan Thomas 
  pic: 2
  tagline: Monitoring freak
  social:
    - title: github
      url: https://github.com/adriaanthomas
    - title: linkedin
      url: https://nl.linkedin.com/pub/adriaan-thomas/0/50a/2bb

- name: Thomas Kruitbosch 
  pic: 3
  tagline: Cloud Engineer
  social:
    - title: github
      url: http://github.com/amochtar
    - title: linkedin
      url: https://nl.linkedin.com/pub/thomas-kruitbosch/0/498/386

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/devopsautomators

# Postal address (add as many lines as necessary)
address:
  - line: Utrechtseweg 49
  - line: 1213 TL  
  - line: The Netherlands

# Build settings
markdown: kramdown
permalink: pretty
