url: http://devopsautomators.io

# Site settings
title: Devopsautomators
tagline: We are software delivery pipeline automation experts!
email: info@devopsautomators.io 
description: "Devopsautomators are experts in automating your software delivery process. We are experienced engineers with a focus on making things work better."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333
  blue: 00b3fe
  green: 8fcb00

# Team names, titles and social links
people:
- name: Bas Tichelaar 
  pic: 1
  tagline: Entreprenerd
  social:
    - title: twitter
      url: https://twitter.com/bastichelaar
    - title: github
      url: http://github.com/bastichelaar
    - title: linkedin 
      url: http://nl.linkedin.com/in/bastichelaar 

- name: Simon van der Veldt 
  pic: 2
  tagline: Hard- and software tinkerer
  social:
    - title: github
      url: http://github.com/simonvanderveldt
    - title: linkedin
      url: https://nl.linkedin.com/in/simonvanderveldt

- name: Ade Mochtar 
  pic: 3
  tagline: Cloud Engineer
  social:
    - title: github
      url: http://github.com/amochtar

- name: Richard Woudenberg 
  pic: 4 
  tagline: Troublemaker
  social:
    - title: linkedin
      url: https://nl.linkedin.com/in/richardwoudenberg  
    - title: github
      url: http://github.com/rchrd


- name: Benny Cornelissen
  pic: 5
  tagline: Infrastructure Hacker
  social: 
    - title: linkedin
      url: https://nl.linkedin.com/in/bennycornelissen
    - title: twitter
      url: https://twitter.com/whieee
    - title: bitbucket
      url: https://bitbucket.org/bcornelissen
    - title: github
      url: http://github.com/bennycornelissen
    
- name: Armin Coralic 
  pic: 6 
  tagline: Dockerizer
  social:
    - title: linkedin
      url: https://nl.linkedin.com/in/armincoralic 
    - title: github
      url: http://github.com/acoralic

- name: Roy Bos 
  pic: 7 
  tagline: Full Stack Developer 
  social:
    - title: linkedin
      url: https://nl.linkedin.com/in/roybos 
    - title: github
      url: http://github.com/roybos


- name: Martin van Steenis 
  pic: 8
  tagline: Firestarter 
  social:
    - title: linkedin
      url: https://nl.linkedin.com/in/martinvansteenis

- name: Fai Fung
  pic: 9
  tagline: DevOps Advocate
  social:
    - title: linkedin
      url: https://nl.linkedin.com/in/faifung
    - title: github
      url: https://github.com/ffung
    - title: twitter
      url: https://twitter.com/fai_fung

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/cargonauts
  - title: github
    url: http://github.com/cargonauts

# Postal address (add as many lines as necessary)
address:
  - line: Utrechtseweg 49
  - line: 1213 TL  
  - line: The Netherlands

# Build settings
markdown: kramdown
permalink: pretty
